config/routes.rb
Tddbenzin::Application.routes.draw do

  resources :cars do
    resources :fillings
  end
  

  devise_for :users

  get "home/index"

   root :to => "home#index"

end

app/models/car.rb
class Car < ActiveRecord::Base
  has_many :fillings
end

app/models/filling.rb
class Filling < ActiveRecord::Base
  belongs_to :car
  
  validates_numericality_of :amount, :price, :odometer
  validates_presence_of :amount, :price, :odometer
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # GET /cars
  # GET /cars.xml
  def index
    @cars = Car.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cars }
    end
  end

  # GET /cars/1
  # GET /cars/1.xml
  def show
    @car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @car }
    end
  end

  # GET /cars/new
  # GET /cars/new.xml
  def new
    @car = Car.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @car }
    end
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
  end

  # POST /cars
  # POST /cars.xml
  def create
    @car = Car.new(params[:car])

    respond_to do |format|
      if @car.save
        format.html { redirect_to(@car, :notice => 'Car was successfully created.') }
        format.xml  { render :xml => @car, :status => :created, :location => @car }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @car.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cars/1
  # PUT /cars/1.xml
  def update
    @car = Car.find(params[:id])

    respond_to do |format|
      if @car.update_attributes(params[:car])
        format.html { redirect_to(@car, :notice => 'Car was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @car.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.xml
  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to(cars_url, :notice => 'Car was successfully deleted.') }
      format.xml  { head :ok }
    end
  end
end

app/controllers/fillings_controller.rb
class FillingsController < ApplicationController
  
  def index
    @car = Car.find(params[:car_id])
    @fillings = @car.fillings
  end
  
  def new
    @car = Car.find(params[:car_id])
    @filling =  @car.fillings.new
  end
  
  def edit
    @car = Car.find(params[:car_id])
    @filling = Filling.find(params[:id])
  end
  
  def create
    @car = Car.find(params[:car_id])
    @filling = @car.fillings.create(params[:filling])
    #puts @car.inspect
    #puts @filling.inspect
    
    if @filling.save
      redirect_to car_fillings_path(@car.id), :notice => "Filling was successfully saved."
    else
      render :action => "new"
    end
    
  end
  
  def update
    @car = Car.find(params[:car_id])
    @filling = Filling.find(params[:id])
    
    if @filling.update_attributes(params[:filling])
      redirect_to car_fillings_path(@car.id), :notice => "Filling was successfully updated."
      
    else
      render :action => "edit"
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/fillings_helper.rb
module FillingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brand %><br />
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %> | 
<%= link_to 'Delete car', @car, :confirm => 'Are you sure?', :method => :delete %>

app/views/cars/index.html.erb
<h1>Listing cars</h1>

<table>
  <tr>
    <th>Brand</th>
    <th>Model</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cars.each do |car| %>
  <tr>
    <td><%= car.brand %></td>
    <td><%= car.model %></td>
    <td><%= car.description %></td>
    <td><%= link_to 'Show', car %></td>
    <td><%= link_to 'Edit', edit_car_path(car) %></td>
    <td><%= link_to 'Destroy', car, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Brand:</b>
  <%= @car.brand %>
</p>

<p>
  <b>Model:</b>
  <%= @car.model %>
</p>

<p>
  <b>Description:</b>
  <%= @car.description %>
</p>


<h1>Listing fillings</h1>

<%= render :partial => 'fillings/fillings', :locals => {:fillings => @car.fillings} %>




<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %> |
<%= link_to 'new filling', new_car_filling_path(@car) %>

app/views/fillings/_fillings.html.erb
<table border="0" cellspacing="5" cellpadding="5" id="fillings">
  <tr>
    <th>Amount</th>
    <th>Price</th>
    <th>Kilometres</th>
  </tr>
  
 
<% if !fillings.blank? %>
  <% fillings.each do |filling| %>
    <tr>
      <td><%= "%.2f" % filling.amount %></td>
      <td><%= "%.2f" % filling.price %></td>
      <td><%= filling.odometer %></td>
      <td><%= link_to 'Edit', edit_car_filling_path(@car, filling) %></td>
      <td><%= link_to 'Destroy', car_filling_path(@car, filling), :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
<% else %>
<tr>
  <td colspan="3">No fillings here.</td>
</tr>
<% end %>
</table>

app/views/fillings/_form.html.erb
<%= form_for [@car, @filling]  do |f| %>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :odometer %><br />
    <%= f.text_area :odometer %>
  </div>
  <div class="actions">
    <%= f.submit "Save filling" %>
  </div>
<% end %>

app/views/fillings/edit.html.erb
<h1>Edit filling</h1>

<%= render 'form' %>

<%= link_to 'Back', car_fillings_path %>

app/views/fillings/index.html.erb
<h1>Listing fillings</h1>


<%= render :partial => 'fillings/fillings', :locals => {:fillings => @car.fillings} %>

app/views/fillings/new.html.erb
<h1>New filling</h1>

<%= render 'form' %>

<%= link_to 'Back', car_fillings_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tddbenzin</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
  
  <div id="user_nav">  
   <% if user_signed_in? %>  
     Signed in as <%= current_user.email %>. Not you?  
   <%= link_to "Sign out", destroy_user_session_path %>  
   <% else %>  
     <%= link_to "Sign up", new_user_registration_path %> or  
     <%= link_to "Sign in", new_user_session_path %>  
   <% end %>  
  </div>

<div id="nav">
<ul>
  <li><%= link_to "Create new car", new_car_path %></li>
</ul>
</div>


<%= yield %>

</body>
</html>